# Installation

In [ ]:
pip install numpy

# Import

In [ ]:
import numpy as np

# Verification

In [ ]:
print(np.__version__)

# Upgrading NumPy

In [ ]:
pip install --upgrade numpy

In [ ]:
import numpy as np
np.__version__

# Upgrade pip

In [ ]:
pip install --upgrade pip

### NumPy Data Types

In [ ]:
import numpy as np

In [ ]:
list1 = [1, 2, 3]

In [ ]:
x = np.array(list1, dtype = np.float32)
y = np.array(list1, dtype = np.uint8)

In [ ]:
print(x, y)

In [ ]:
print(type(x), type(y))

# Indexing

In [ ]:
import numpy as np
x = np.array([1, 2, 3],
             dtype = np.float32)

In [ ]:
x[0]

In [ ]:
x[1]

In [ ]:
x[2]

In [ ]:
x[3]

## Negative Indexing

In [ ]:
import numpy as np
x = np.array([1, 2, 3],
             dtype = np.float32)

In [ ]:
x[-1]

In [ ]:
x[-2]

In [ ]:
x[-3]

In [ ]:
x[-4]

### Multidimensional Arrays

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.uint8)

In [ ]:
x

In [ ]:
# Row , Column
x[0, 0]

In [ ]:
x[0, 1]

In [ ]:
# Access full column
x[:, 0]

In [ ]:
# Access full Row
x[0, :]

#### 3D Arrays and Indexing

In [ ]:
import numpy as np
x = np.array([[[1, 2, 3], [4, 5, 6]],
              [[2, 3, 4], [0, 2, 1]]], 
             dtype=np.uint8)

In [ ]:
x

In [ ]:
x[1, :, 0]

In [ ]:
x[1, :, :]

In [ ]:
x[:, :, 0]

#### Empty Arrays

In [ ]:
import numpy as np

x = np.array([])

In [ ]:
x

In [ ]:
type(x)

In [ ]:
np.array([[],[]])

In [ ]:
np.array([[[], []],
          [[], []]])

#### Ndarray Properties

In [ ]:
import numpy as np
x = np.array([[[1, 2, 3], [4, 5, 6]],
              [[2, 3, 4], [0, 2, 1]]], 
             dtype=np.uint8)

In [ ]:
x

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
x.dtype

In [ ]:
x.size

In [ ]:
x.nbytes

### NumPy Constants

In [ ]:
np.inf

In [ ]:
np.NAN

In [ ]:
np.NINF

In [ ]:
np.NZERO

In [ ]:
np.PZERO

In [ ]:
np.e

In [ ]:
np.euler_gamma

In [ ]:
np.pi

### Initiate empty Ndarray

In [ ]:
import numpy as np
x = np.empty(3)
x

In [ ]:
x = np.empty((3, 3))
x

In [ ]:
x = np.empty((3, 3), dtype = np.int16)
x

In [ ]:
x = np.empty((3, 3, 2), dtype = np.int16)
x

#### Identity Matrix

In [ ]:
import numpy as np
x = np.eye(4, dtype = np.int16)
x

In [ ]:
x = np.eye(4, k=-1)
x

In [ ]:
x = np.eye(4, k=1)
x

In [ ]:
#x = np.eye(4)
x = np.eye(4, k=0)
x

#### Identity Matrix

In [ ]:
import numpy as np
x = np.identity(5)
x

In [ ]:
x = np.identity(5, dtype=np.uint8)
x

### Matrix of ones

In [ ]:
import numpy as np
x = np.ones(5)
x

In [ ]:
x = np.ones((5, 3, 2), np.uint8)
x

### Matrix of Zeros

In [ ]:
import numpy as np
x = np.zeros(5)
x

In [ ]:
import numpy as np
x = np.zeros((5, 2, 3), np.int16)
x

### Tringular matrices

In [ ]:
import numpy as np
x = np.tri(3)
x

In [ ]:
x = np.tri(3, dtype=np.uint8)
x

In [ ]:
x = np.tri(5, 4, k = -1, dtype=np.uint8)
x

#### Lower triangular matrices

In [42]:
import numpy as np
x = np.ones((5, 5), np.uint16)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint16)

In [43]:
y = np.tril(x)
y

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]], dtype=uint16)

In [44]:
y = np.tril(x, k = -1)
y

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]], dtype=uint16)

In [45]:
y = np.tril(x, k = 1)
y

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint16)

#### Full Matrix

In [46]:
import numpy as np
x = np.full((2, 3 ,5), dtype=np.uint8,
           fill_value = 4)
x

array([[[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]], dtype=uint8)

#### Upper Triangular Matrix

In [47]:
import numpy as np
x = np.ones((5, 5), np.uint16)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint16)

In [48]:
y = np.triu(x)
y

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]], dtype=uint16)

In [49]:
y = np.triu(x, k = 2)
y

array([[0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint16)

In [50]:
y = np.triu(x, k = -3)
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1]], dtype=uint16)